name: Cek Proxy Otomatis

on:
  push:
    branches: [ main ]

jobs:
  run-proxy-checker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install axios

    - name: Jalankan pengecekan proxy
      run: node proxy-checker.js

    - name: Upload hasil cek proxy
      uses: actions/upload-artifact@v4
      with:
        name: hasil-cek-proxy
        path: results.txt
